### ISSUE TITLE
errrors after uploding the emails

### ISSUE THREAD

**Issue by dkusypmi** [molotochok/msg-viewer#3]
hello,
When I upload some emails (with .msg) I'm getting the two following errors:

An error occured during the parsing of the .msg file. Error: TypeError: Cannot read properties of undefined (reading 'byteLength')

An error occured during the parsing of the .msg file. Error: TypeError: Cannot read properties of undefined (reading 'endsWith')

**Comment by molotochok** [comment]
The problem is that if .msg file is attached to .msg file then it is treated as an embedded file. There is no content that can be easily downloadable as for other files. I am working on fixing this.

**Comment by molotochok** [comment]
I just submitted a fix that should fix this issue. Now, if the file contains another .msg file inside then a button should be rendered which if clicked will show the content of the inner file.
